In [2]:
import numpy as np
np.__version__

'1.20.3'

파이썬 리스트에서 배열 만들기

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
np.array([3.14, 4, 2, True, False])

array([3.14, 4.  , 2.  , 1.  , 0.  ])

In [6]:
np.array([3.14, 4, 2, True, False], dtype = 'int')

array([3, 4, 2, 1, 0])

In [7]:
np.array([[range(i, i + 3) for i in [2, 4, 6]]])

array([[[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]]])

처음부터 배열 만들기

In [8]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((4, 6), 358.123)

array([[358.123, 358.123, 358.123, 358.123, 358.123, 358.123],
       [358.123, 358.123, 358.123, 358.123, 358.123, 358.123],
       [358.123, 358.123, 358.123, 358.123, 358.123, 358.123],
       [358.123, 358.123, 358.123, 358.123, 358.123, 358.123]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 2, 11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [17]:
np.random.random((3, 3))

array([[0.44695491, 0.00340389, 0.62198781],
       [0.99113184, 0.6107725 , 0.2337093 ],
       [0.99196578, 0.33463815, 0.66912796]])

In [30]:
np.random.normal(0, 1, (3, 3))

array([[ 0.88805669,  0.52538917, -0.76801322],
       [-0.37273841, -0.61464181,  0.5866801 ],
       [ 1.47143522, -0.69465483,  0.58992052]])

In [25]:
np.random.randint(-5, 5, (3, 3))

array([[-1, -5,  1],
       [ 0, -2,  4],
       [-5, -1,  4]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.empty((3,3))

array([[0.88805669, 0.52538917, 0.76801322],
       [0.37273841, 0.61464181, 0.5866801 ],
       [1.47143522, 0.69465483, 0.58992052]])

In [35]:
x = np.array([[i*5 + j for j in range(5)] for i in range(5)])
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
x[1:5:2, 0:4:2]

array([[ 5,  7],
       [15, 17]])

In [37]:
x[::-1, ::-1]

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])